--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/famima65536/StrictFormExample
build-by-default: true
branches:
- master
projects:
  StrictFormExample:
    path: ""
    libs: 
      src: "OiranCage/StrictForm/StrictForm"
      version: ^1.0.0
...
